const data = [
    {
        id: 1,
        title: "The Ultimate Remote Developer Setup: Top Tools for Communication and Productivity",
        img: "blog01.jpg",
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 2,
        title: "The Rise of AI-Assisted Coding: GitHub Copilot vs. Amazon CodeWhisperer vs. Tabnine",
        img: "blog02.jpg",
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 3,
        title: "How to Choose the Right Database for Your Project",
        img: "blog03.jpg",
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 4,
        title: "From Idea to MVP: Our 6-Step Process for Launching a Successful Mobile App",
        img: "blog04.jpg",
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 5,
        title: "Beyond Code: The Real Value a Full-Cycle Development Team Brings to Your Project",
        img: "blog05.jpg",
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 6,
        title: "5 Hidden Costs of Choosing the Wrong Software Development Partner",
        img: "blog06.jpg",
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 7,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog07.jpg",
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2026",
    },
    {
        id: 8,
        title: "Observable universes each of which would comprise",
        img: "blog08.jpg",
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2026",
    },
];
export default data;
